### ISSUE TITLE
[Urgent] Please request PR before merging to master branch

### ISSUE THREAD

**Issue by HyeongGunLee** [ZZelly/timo-tiver#1]
@markers2 @markers2 @markers2 
Please create PR before merging to Master branch. OK?OK?OK?
and we can exclude `build` directory(no reason to include in git repo) from `.gitignore`

**Comment by markers2** [comment]
I have created PR before merging, so there is no issue about it!
By the way, could you please make `.gitignore` by yourself?
Thanks.

**Comment by HyeongGunLee** [comment]
What's that emoji?! please smile. OK?OK?OK?
Where is PR? assign to me. OK?OK?OK?
It's better you to create the `.gitignore` OK?OK?OK?

No Thanks,

**Comment by markers2** [comment]
Done
